name: xGenONTAssembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=1.2.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.6.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - bcftools=1.15.1
  - bedtools=2.30.0
  - bioawk=1.0
  - biopython=1.79
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2022.6.15.2
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - coreutils=9.1
  - cryptography=37.0.4
  - curl=7.83.1
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - frozenlist=1.3.1
  - gast=0.4.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpc-cpp=1.43.2
  - grpcio=1.43.0
  - gsl=2.7
  - h5py=3.7.0
  - harfbuzz=5.1.0
  - hdf5=1.12.2
  - htslib=1.15.1
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - intervaltree=3.0.2
  - jpeg=9e
  - k8=0.2.5
  - keras=2.7.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=7.83.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.12
  - longshot=0.4.5
  - mappy=2.24
  - markdown=3.4.1
  - markupsafe=2.1.1
  - medaka=1.7.1
  - minimap2=2.24
  - multidict=6.0.2
  - ncurses=6.3
  - nextflow=22.04.5
  - numpy=1.19.5
  - oauthlib=3.2.0
  - ont-fast5-api=4.0.2
  - openjdk=17.0.3
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - packaging=21.3
  - parasail-python=1.3.3
  - pcre=8.45
  - perl=5.32.1
  - pip=22.2.2
  - pixman=0.40.0
  - primerclip=0.3.8
  - progressbar33=2.4
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysam=0.19.1
  - pysocks=1.7.1
  - pyspoa=0.0.3
  - python=3.8.13
  - python-edlib=1.3.9
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pyu2f=0.1.5
  - re2=2022.02.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - samtools=1.15.1
  - scipy=1.9.0
  - setuptools=65.3.0
  - six=1.16.0
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - sqlite=3.39.2
  - tar=1.34
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.7.1
  - tensorflow-base=2.7.1
  - tensorflow-estimator=2.7.1
  - termcolor=1.1.0
  - tk=8.6.12
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - vcftools=0.1.16
  - werkzeug=2.2.2
  - wheel=0.37.1
  - wrapt=1.14.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yarl=1.7.2
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pyvcf3==1.0.3
